ipAddr: localhost
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://${ipAddr}:3306/gulimall_pms?serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: gulimall-product

  redis:
    host: 192.168.56.10
    port: 6379
  #设置缓存类型
  cache:
    type: redis
    # 设置存活时间
    redis:
      time-to-live: 3600000
      #      如果指定了前缀就用我们指定的 如果没有就用缓存的名字作为前缀
      #      key-prefix: CACHE_
      #      是否缓存空值
      cache-null-values: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  thymeleaf:
    cache: false
    suffix: .html
    prefix: classpath:/templates/
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      # 配置逻辑删除 1代表删除 0代表已删除
      logic-delete-value: 1
      logic-not-delete-value: 0
server:
  port: 10002
logging:
  level:
    com.atguigu.gulimall: debug
gulimall:
  thread:
    core-size: 10
    max-size: 50
    keep-alive-time: 10
    block-deque-length: 100
