spring:
  application:
    name: gulimall-third-party
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      access-key: LTAI5tLLLxjitMC4z9gGt6fM
      secret-key: A9M865chJsNAjsBWzete1D2SLjsFew
      oss:
        endpoint: oss-cn-beijing.aliyuncs.com
        bucket: gulimall-yanglvjin
server:
  port: 30000
