spring:
  application:
    name: gulimall-cart
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  session:
    store-type: redis
  redis:
    host: 192.168.56.10
server:
  port: 40000
gulimall:
  thread:
    core-size: 20
    max-size: 200
    keep-alive-time: 10